# Generated by Django 4.1.4 on 2023-01-27 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0006_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
